# Overriding configuration when started in local mode
# to start in local with maven: -Dspring-boot.run.profiles=local

spring:
  rabbitmq:
    host: localhost

info:
  application:
    name: '@project.name@ (local deployment)'

app:
  bank-route: http://localhost:50000/bank/request
  payslip-route: http://localhost:50500/payslip/request

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/