spring:
  application:
    name: payment-service
    datasource:
      username: sa
      password: password
      driverClassName: org.h2.Driver
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
      defer-datasource-initialization: true
  rabbitmq:
    username: admin
    password: cas735

logging.level:
  ca.mcmaster.cas735.group2.payment-service:
    adapter:  INFO
    business: INFO

server:
  port: 9082

app:
  exchange: pac.exchange

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: info,health
      base-path: /actuator

info:
  application:
    description: '@project.description@'
    version:     '@project.version@'

eureka:
  client:
    healthcheck:
      enabled: true
