include:
  - ./../infrastructure/docker-compose.yml

services:
  entry-gate:
    container_name: entry-gate
    build:
      context: ../services/entry-gate
    ports:
      - "9080:9080"
    networks:
      - shared-network
    depends_on:
      rabbitmq:
        condition: service_healthy
      service-registry:
        condition: service_healthy

  exit-gate:
    container_name: exit-gate
    build:
      context: ../services/exit-gate
    ports:
      - "9081:9081"
    networks:
      - shared-network
    depends_on:
      rabbitmq:
        condition: service_healthy
      service-registry:
        condition: service_healthy

  lot:
    container_name: lot
    build:
      context: ../services/lot
    ports:
      - "9082:9082"
    networks:
      - shared-network
    volumes:
      - type: bind
        source: ${PWD}/data
        target: /data
    depends_on:
      rabbitmq:
        condition: service_healthy
      service-registry:
        condition: service_healthy

  payment-service:
    container_name: payment-service
    build:
      context: ../services/payment-service
    ports:
      - "9083:9083"
    networks:
      - shared-network
    volumes:
      - type: bind
        source: ${PWD}/data
        target: /data
    depends_on:
      rabbitmq:
        condition: service_healthy
      service-registry:
        condition: service_healthy

  permit:
    container_name: permit
    build:
      context: ../services/permit
    ports:
      - "9084:9084"
    networks:
      - shared-network
    volumes:
      - type: bind
        source: ${PWD}/data
        target: /data
    depends_on:
      rabbitmq:
        condition: service_healthy
      service-registry:
        condition: service_healthy

  voucher-service:
    container_name: voucher-service
    build:
      context: ../services/voucher-service
    ports:
      - "9085:9085"
    networks:
      - shared-network
    volumes:
      - type: bind
        source: ${PWD}/data
        target: /data
    depends_on:
      rabbitmq:
        condition: service_healthy
      service-registry:
        condition: service_healthy

  fines:
    container_name: fines
    build:
      context: ../services/fines
    ports:
      - "9086:9086"
    networks:
      - shared-network
    volumes:
      - type: bind
        source: ${PWD}/data
        target: /data
    depends_on:
      rabbitmq:
        condition: service_healthy
      service-registry:
        condition: service_healthy

networks:
  shared-network:
    external: true
