spring:
  application:
    name: admin
  ## Data repository configuration

  rabbitmq:
    username: admin
    password: cas735
    host: localhost

app:
  custom:
    messaging:
      exchange: pac.exchange

server:
  port: 9091


# Info about the client
info:
  application:
    description: '@project.description@'
    version:     '@project.version@'
